function [fitresult, gof] = createFit(testX, testY)
%CREATEFIT(TESTX,TESTY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : testX
%      Y Output: testY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Apr-2020 22:08:52


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( testX, testY );

% Set up fittype and options.
ft = fittype( 'poly9' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'testY vs. testX', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'testX', 'Interpreter', 'none' );
ylabel( 'testY', 'Interpreter', 'none' );
grid on


