function [subsets1, boundaries1, subsets2, boundaries2] = PC2HM_partitionPointCloudRecursive(points1, values1, points2, values2, minCoords, maxCoords, MaxSumPerCube, DividingFactor, ExpansionFactor,...
    subsets1, boundaries1, subsets2, boundaries2)

% Check if the cumulative sum of values within the cube exceeds the threshold
if max(sqrt(sum(values1)^2 + sum(values2)^2),values2) > MaxSumPerCube
    
    % Divide the cube into smaller cubes
    [subMinCoords, subMaxCoords] = PC2HM_divideCube(minCoords, maxCoords, DividingFactor);
    
    % Recursively partition each of the smaller cubes
    for i = 1:size(subMinCoords, 1)
        subPoints1 = points1((points1(:,1) >= subMinCoords(i,1)) & (points1(:,1) <= subMaxCoords(i,1)) & ...
                           (points1(:,2) >= subMinCoords(i,2)) & (points1(:,2) <= subMaxCoords(i,2)),:);
        subValues1 = values1((points1(:,1) >= subMinCoords(i,1)) & (points1(:,1) <= subMaxCoords(i,1)) & ...
                           (points1(:,2) >= subMinCoords(i,2)) & (points1(:,2) <= subMaxCoords(i,2)));
        subPoints2 = points2((points2(:,1) >= subMinCoords(i,1) - (subMaxCoords(i,1) - subMinCoords(i,1))*(ExpansionFactor - 1)/2) &...
            (points2(:,1) <= subMaxCoords(i,1) + (subMaxCoords(i,1) - subMinCoords(i,1))*(ExpansionFactor - 1)/2) & ...
            (points2(:,2) >= subMinCoords(i,2) - (subMaxCoords(i,2) - subMinCoords(i,2))*(ExpansionFactor - 1)/2) &...
            (points2(:,2) <= subMaxCoords(i,2) + (subMaxCoords(i,2) - subMinCoords(i,2))*(ExpansionFactor - 1)/2),:);
        subValues2 = values2((points2(:,1) >= subMinCoords(i,1) - (subMaxCoords(i,1) - subMinCoords(i,1))*(ExpansionFactor - 1)/2) &...
            (points2(:,1) <= subMaxCoords(i,1) + (subMaxCoords(i,1) - subMinCoords(i,1))*(ExpansionFactor - 1)/2) & ...
            (points2(:,2) >= subMinCoords(i,2) - (subMaxCoords(i,2) - subMinCoords(i,2))*(ExpansionFactor - 1)/2) &...
            (points2(:,2) <= subMaxCoords(i,2) + (subMaxCoords(i,2) - subMinCoords(i,2))*(ExpansionFactor - 1)/2));
        [subsets1, boundaries1, subsets2, boundaries2] = PC2HM_partitionPointCloudRecursive(...
            subPoints1, subValues1, subPoints2, subValues2, subMinCoords(i,:), subMaxCoords(i,:),...
            MaxSumPerCube, DividingFactor, ExpansionFactor,...
            subsets1, boundaries1, subsets2, boundaries2);
    end
else
    % Add the subset and boundary to the list
    subsets1{end+1} = points1;
    boundaries1{end+1} = [minCoords; maxCoords];
    subsets2{end+1} = points2;
    boundaries2{end+1} = [...
        minCoords - (maxCoords - minCoords)*(ExpansionFactor - 1)/2;...
        maxCoords + (maxCoords - minCoords)*(ExpansionFactor - 1)/2];
end

end
